name: Feature Request
description: Suggest an idea for Data Warden
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please check the [ROADMAP.md](https://github.com/tazgreenwood/data-warden/blob/main/ROADMAP.md) first to see if it's already planned.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also thought about...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Tools
      description: Are there other database tools that have this feature?
      placeholder: |
        - Tool X does this by...
        - Tool Y has a similar feature...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Would you be willing to contribute this feature?
      description: We welcome contributions!
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
      placeholder: Additional details...
    validations:
      required: false
